<div class="grmn-section-container">
	<div class="grmn-uix-expander grmn-uix-expander-collapsed">
		<h3 class="branded-page-module-title">Latest videos</h3>
		<?php if($this->latestVideoItems):?>
		<ul class="shelf-content clearfix grmn-uix-expander-body" id="video_stage">
			<?php foreach ($this->latestVideoItems as $videoItem):?>
			<li class="grmn-shelf-grid-item1">
		  		<div class="grmn-lockup-thumbnail" <?php if($videoItem->watched):?>style="opacity: 0.5; filter: alpha(opacity=50);"<?php endif;?>>
			        <?php if($videoItem->isNew and !$videoItem.watched):?>
			        <span class="grmn-video-new"></span>
			        <?php endif;?>
			        <a target="_blank" href="<?php echo $this->baseURL;?>watch?v=<?php echo $videoItem->videoId;?><?php if(isset($_REQUEST["youtube"])):?>&youtube<?php endif;?>" 
			        	title="<?php echo $videoItem->title;?>" 
			        	class="ux-thumb-wrap">
			        	<span class="video-thumb  grmn-thumb">
					      <span class="grmn-thumb-default">
					        <span class="grmn-thumb-clip">
					        	<?php if(isset($_REQUEST["youtube"])):?>
					      		<img alt="thumbnail" src="<?php echo $videoItem->thumb;?>" data-thumb="<?php echo $videoItem->thumb;?>" width="400" height="260">
					          	<span class="vertical-align"></span>
					        	<?php else:?>
					      		<img alt="thumbnail" src="<?php echo $this->baseURL;?>static/images/<?php echo $videoItem->localThumb;?>" data-thumb="<?php echo $videoItem->localThumb;?>" width="400" height="260">
					        	<?php endif;?>
					        </span>
					      </span>
					    </span>
					</a>
			    </div>
				<div class="grmn-lockup-content">
					<h3 class="grmn-lockup-title" <?php if($videoItem->watched):?>style="opacity: 0.5; filter: alpha(opacity=50);"<?php endif;?>>
						<a target="_blank" title="<?php echo $videoItem->title;?>" href="watch?v=<?php echo $videoItem->videoId;?><?php if(isset($_REQUEST["youtube"])):?>&youtube<?php endif;?>" dir="ltr">
						<?php echo $videoItem->title;?>
						</a>
					</h3>
				</div>
				<div class="grmn-lockup-meta">
				    <ul class="grmn-lockup-meta-info">
				        <li class="grmn-lockup-deemphasized-text">
				        	Upload: <?php echo substr($videoItem->createdAt, 0, 10);?>
				        </li>
				    </ul>
				</div>			    	        							
			</li>
			<?php endforeach;?>
		</ul>
		<div id="latest_first">
			<?php if($this->latestVideoItems):?>
			<?php if($this->latestVideoItems[0]): $videoItem = $this->latestVideoItems[0];?>
		  		<div class="grmn-lockup-thumbnail latest" <?php if($videoItem->watched):?>style="opacity: 0.5; filter: alpha(opacity=50);"<?php endif;?>>
			        <?php if($videoItem->isNew and !$videoItem.watched):?>
			        <span class="grmn-video-new"></span>
			        <?php endif;?>
			        <a target="_blank" href="<?php echo $this->baseURL;?>watch?v=<?php echo $videoItem->videoId;?><?php if(isset($_REQUEST["youtube"])):?>&youtube<?php endif;?>" 
			        	title="<?php echo $videoItem->title;?>" 
			        	class="ux-thumb-wrap">
			        	<span class="video-thumb  grmn-thumb">
					      <span class="grmn-thumb-default">
					        <span class="grmn-thumb-clip">
					        	<?php if(isset($_REQUEST["youtube"])):?>
					      		<img alt="thumbnail" src="<?php echo $videoItem->thumb;?>" data-thumb="<?php echo $videoItem->thumb;?>" width="400" height="260">
					          	<span class="vertical-align"></span>
					        	<?php else:?>
					      		<img alt="thumbnail" src="<?php echo $this->baseURL;?>static/images/<?php echo $videoItem->localThumb;?>" data-thumb="<?php echo $videoItem->localThumb;?>" width="400" height="260">
					        	<?php endif;?>
					        </span>
					      </span>
					    </span>
					</a>
			    </div>
				<div class="grmn-lockup-content">
					<h3 class="grmn-lockup-title" <?php if($videoItem->watched):?>style="opacity: 0.5; filter: alpha(opacity=50);"<?php endif;?>>
						<a target="_blank" title="<?php echo $videoItem->title;?>" href="<?php echo $this->baseURL;?>watch?v=<?php echo $videoItem->videoId;?><?php if(isset($_REQUEST["youtube"])):?>&youtube<?php endif;?>" dir="ltr">
						<?php echo $videoItem->title;?>
						</a>
					</h3>
				</div>
				<div class="grmn-lockup-meta">
				    <ul class="grmn-lockup-meta-info">
				        <li class="grmn-lockup-deemphasized-text">
				        	Upload: <?php echo substr($videoItem->createdAt, 0, 10);?>
				        </li>
				    </ul>
				</div>
			<?php endif;?>
			<?php endif;?>				
		</div>
		<?php else:?><div style="padding-left: 5px;">No videos</div>
		<?php endif;?>
		<ul class="shelf-content clearfix grmn-uix-expander-body" id="video_back_stage">
			<?php if($this->latestVideoItems):?>
				<?php foreach ($this->latestVideoItems as $videoItem):?>
				<li class="grmn-shelf-grid-item latest">
			  		<div class="grmn-lockup-thumbnail latest" <?php if($videoItem->watched):?>style="opacity: 0.5; filter: alpha(opacity=50);"<?php endif;?>>
				        <?php if($videoItem->isNew and !$videoItem.watched):?>
				        <span class="grmn-video-new"></span>
				        <?php endif;?>
				        <a target="_blank" href="<?php echo $this->baseURL;?>watch?v=<?php echo $videoItem->videoId;?><?php if(isset($_REQUEST["youtube"])):?>&youtube<?php endif;?>" 
				        	title="<?php echo $videoItem->title;?>" 
				        	class="ux-thumb-wrap">
				        	<span class="video-thumb  grmn-thumb">
						      <span class="grmn-thumb-default">
						        <span class="grmn-thumb-clip">
						        	<?php if(isset($_REQUEST["youtube"])):?>
						      		<img alt="thumbnail" src="<?php echo $videoItem->thumb;?>" data-thumb="<?php echo $videoItem->thumb;?>" width="80">
						          	<span class="vertical-align"></span>
						        	<?php else:?>
						      		<img alt="thumbnail" src="<?php echo $this->baseURL;?>static/images/<?php echo $videoItem->localThumb;?>" data-thumb="<?php echo $videoItem->localThumb;?>" width="80">
						        	<?php endif;?>
						        </span>
						      </span>
						    </span>
						</a>
				    </div>	        							
				</li>
				<?php endforeach;?>
			<?php endif;?>
		</ul>
	</div>
</div>