<div class="grmn-section-container" style="z-index: 2; min-height: 300px;">
	<div class="grmn-uix-expander grmn-uix-expander-collapsed">
		<h3 class="branded-page-module-title">
			More videos<span style="font-weight: normal; font-size: 14px;">(<?php echo $this->totals;?>)</span>
			<span id="category_container"
			data-baseurl="<?php echo $this->baseURL;?>" data-youtube="<?php if(isset($_REQUEST['youtube'])):?>youtube<?php endif;?>" data-qs=<?php $this->queryStringNoCat?>>
				<span <?php if($this->catUI != "2"):?>style="display: none;"<?php endif;?>>
					by 
					<select id="category_by" >
						<option value="" <?php if($this->category == 'all'):?>selected<?php endif;?>>All</option>
						<option value="garmin" <?php if($this->category == 'garmin'):?>selected<?php endif;?>>Garmin</option>
						<option value="ted" <?php if($this->category == 'ted'):?>selected<?php endif;?>>TED</option>
						<option value="famous" <?php if($this->category == 'famous'):?>selected<?php endif;?>>Famous</option>
						<option value="others" <?php if($this->category == 'others'):?>selected<?php endif;?>>Others</option>
					</select>									
				</span>
				<span <?php if($this->catUI != "1"):?>style="display: none;"<?php endif;?>>
					<span class="grmn-video-category <?php if($this->category == 'all'):?>grmn-video-category-checked<?php endif;?>" title="all" style="margin-left: 0px;">
						<input type="radio" name="category" value="" <?php if($this->category == 'all'):?>checked<?php endif;?>/> All
					</span>
					<span class="grmn-video-category <?php if($this->category == 'garmin'):?>grmn-video-category-checked<?php endif;?>" title="garmin">
						<input type="radio" name="category" value="garmin" <?php if($this->category == 'garmin'):?>checked<?php endif;?>/> Garmin
					</span>
					<span class="grmn-video-category <?php if($this->category == 'ted'):?>grmn-video-category-checked<?php endif;?>" title="ted">
						<input type="radio" name="category" value="ted" <?php if($this->category == 'ted'):?>checked<?php endif;?>/> TED
					</span>
					<span class="grmn-video-category <?php if($this->category == 'famous'):?>grmn-video-category-checked<?php endif;?>" title="famous">
						<input type="radio" name="category" value="famous" <?php if($this->category == 'famous'):?>checked<?php endif;?>/> Famous
					</span>
					<span class="grmn-video-category <?php if($this->category == 'others'):?>grmn-video-category-checked<?php endif;?>" title="others">
						<input type="radio" name="category" value="others" <?php if($this->category == 'others'):?>checked<?php endif;?>/> Others
					</span>										
				</span>							
			</span>
		</h3>		

	  	<ul class="shelf-content clearfix grmn-uix-expander-body">
		  <?php if($this->videoItems):?>
		  	<?php foreach ($this->videoItems as $videoItem):?>
		  	<li class="grmn-shelf-grid-item">
		  		<div class="grmn-lockup-thumbnail" <?php if($videoItem->watched):?>style="opacity: 0.5; filter: alpha(opacity=50);"<?php endif;?>>
			        <?php if($videoItem->isNew and !$videoItem.watched):?>
			        <span class="grmn-video-new"></span>
			        <?php endif;?>
			        <a target="_blank" href="<?php echo $this->baseURL;?>watch?v=<?php echo $videoItem->videoId;?><?php if(isset($_REQUEST["youtube"])):?>&youtube<?php endif;?>" 
			        	title="<?php echo $videoItem->title;?>" 
			        	class="ux-thumb-wrap grmn-uix-sessionlink grmn-fluid-thumb-link contains-addto  spf-link">
			        	<span class="video-thumb  grmn-thumb grmn-thumb-175 grmn-thumb-fluid">
					      <span class="grmn-thumb-default">
					        <span class="grmn-thumb-clip">
					        	<?php if(isset($_REQUEST["youtube"])):?>
					      		<img alt="thumbnail" src="<?php echo $videoItem->thumb;?>" data-thumb="<?php echo $videoItem->thumb;?>" width="175">
					          	<span class="vertical-align"></span>
					        	<?php else:?>
					      		<img alt="thumbnail" src="<?php echo $this->baseURL;?>static/images/<?php echo $videoItem->localThumb;?>" data-thumb="<?php echo $videoItem->localThumb;?>" width="175">
					        	<?php endif;?>
					        </span>
					      </span>
					    </span>
					    <span class="video-time"><?php echo $videoItem->duration;?></span>
					</a>
			    </div>
				<div class="grmn-lockup-content">
					<h3 class="grmn-lockup-title" <?php if($videoItem->watched):?>style="opacity: 0.5; filter: alpha(opacity=50);"<?php endif;?>>
						<a target="_blank" title="<?php echo $videoItem->title;?>" href="<?php echo $this->baseURL;?>watch?v=<?php echo $videoItem->videoId;?><?php if(isset($_REQUEST["youtube"])):?>&youtube<?php endif;?>" dir="ltr">
						<?php echo $videoItem->title;?>
						</a>
					</h3>
				</div>
				<div class="grmn-lockup-meta">
				    <ul class="grmn-lockup-meta-info">
				        <li>
							Author: <span class="grmn-meta-info-by"><?php echo $videoItem->by;?></span>
				        </li>
				      	<li>
				      		<span class="grmn-meta-info-clkcount"><?php echo $videoItem->clkCount;?></span> Clicks
				      	</li>
				      	<li>
				      		<span class="grmn-meta-info-viewcount"><?php echo $videoItem->localViewCount;?></span> Views
				      	</li>											      	
				        <li class="grmn-lockup-deemphasized-text">
				        	Upload: <?php echo substr($videoItem->createdAt, 0, 10);?>
				        </li>
				    </ul>
				</div>
			</li>
		    <?php endforeach;?>
		    <?php else:?>
		    <li>
		    	<p style="text-align: center;">No videos
		    		<span style="display: none;">, you may go <a href="<?php echo $this->baseURL;?>static/html/videoupload.html" title="Video upload">video upload</a> page to upload YouTube videos</span>
		    	</p>
		    </li>
		   <?php endif;?>
	  	</ul>
        <div class="grmn-uix-expander-head hidden-expander grmn-uix-page">
        	<?php if($this->first):?>
        		<span class="grmn-uix-page-num">
      				<a title="First page" href="<?php echo $this->baseURL;?>page/<?php echo $this->first;?>/<?php if($this->queryString): echo $this->queryString; endif;?>">&lt;&lt;</a>
      			</span>
      		<?php endif;?>
        	<?php if($this->pre):?>
          	<span class="multirow-shelf-expander grmn-uix-page-num">
          		<a title="Previous page" href="<?php echo $this->baseURL;?>page/<?php echo $this->pre;?>/<?php if($this->queryString): echo $this->queryString; endif;?>">&lt;</a>
          	</span>
          	<?php endif;?>
      		<?php foreach ($this->pageCountList as $i): if($i != $this->pageNum):?>
      			<span class="grmn-uix-page-num">
      				<a title="<?php echo $i;?>" href="<?php echo $this->baseURL;?>page/<?php echo $i;?>/<?php if($this->queryString): echo $this->queryString; endif;?>"><?php echo $i;?></a>
      			</span>
      			<?php else:?>
      			<span class="grmn-uix-page-num grmn-uix-page-current"><?php echo $i;?></span>
      			<?php endif;?>
      		<?php endforeach;?>
          	<?php if($this->next):?>
			<span class="multirow-shelf-collapser grmn-uix-page-num">
				<a title="Next page" href="<?php echo $this->baseURL;?>page/<?php echo $this->next;?>/<?php if($this->queryString): echo $this->queryString; endif;?>">&gt;</a>
			</span>							          	
          	<?php endif;?>
        	<?php if($this->last):?>
        		<span class="grmn-uix-page-num">
      				<a title="Last page" href="<?php echo $this->baseURL;?>page/<?php echo $this->last;?>/<?php if($this->queryString): echo $this->queryString; endif;?>">&gt;&gt;</a>
      			</span>
        	<?php endif;?>				          	
        </div>
  	</div>
</div>