<!DOCTYPE html>
<html lang="zh-CN">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta http-equiv="X-UA-Compatible" content="edge" />			
		<title>Garmin Video Sharing</title>
		<link rel="stylesheet" type="text/css" href="/garminvideos/static/css/garminvideos.src.css"/>
		<script type="text/javascript" src="/garminvideos/static/js/jquery/1.7.2.js"></script>
	</head>
	<body>
		<div style="text-align: center; font-weight: bold; font-size: 20px; margin: 10px 0;">
			<a href="/garminvideos/" id="grmn_title" title="Garmin Video Sharing">Garmin Video Sharing</a>
			{% if upload %}
			<a href="/garminvideos/static/html/videoupload.html" id="grmn_videodownloadlink" title="video upload page" target="_blank"> - Upload</a>			
			{% endif %}
		</div>
		<div style="width: 951px; margin: 0 auto 20px;">
			<li class="">
	        	<div class="shelf-wrapper">
	        	</div>
			</li>
		</div>
	</body>
	<script type="text/javascript" src="/garminvideos/static/js/garminvideos.src.js"></script>
</html>